FROM maven:3.8.3-jdk-11 AS build
WORKDIR /build
COPY ./pom.xml /build/pom.xml
COPY ./commons /build/commons
COPY ./rest-consumer /build/rest-consumer
COPY ./kafka-consumer /build/kafka-consumer
RUN mvn clean package -DskipTests=true

FROM openjdk:11
WORKDIR /app
COPY --from=build /build/rest-consumer/target/*.jar ./app.jar
VOLUME /app/config
EXPOSE 8080/tcp
ENTRYPOINT ["java","-jar","/app/app.jar"]